### ISSUE TITLE
feat(postgres): extract user access

### ISSUE THREAD

**Issue by StewartJingga** [odpf/meteor#335]
**Is your feature request related to a problem? Please describe.**
I need to have more metadata from postgres such as db users that have access to the table/dataset.

**Describe the solution you'd like**
Users access information on table metadata using postgres extractor

**Comment by GrayFlash** [comment]
I think this query can be utilised here:

`SELECT * FROM information_schema.role_table_grants;`

Output:
 grantor | grantee | table_catalog |    table_schema    |              table_name               | privilege_type | is_grantable | with_hierarchy 
 root    | root    | root          | pg_catalog         | pg_statistic                          | INSERT         | YES          | NO
 root    | root    | root          | pg_catalog         | pg_statistic                          | SELECT         | YES          | YES
 root    | root    | root          | pg_catalog         | pg_statistic                          | UPDATE         | YES          | NO
 root    | root    | root          | pg_catalog         | pg_statistic                          | DELETE         | YES          | NO
 root    | root    | root          | pg_catalog         | pg_statistic                          | TRUNCATE       | YES          | NO
 root    | root    | root          | pg_catalog         | pg_statistic                          | REFERENCES     | YES          | NO
 root    | root    | root          | pg_catalog         | pg_statistic                          | TRIGGER        | YES          | NO
 root    | root    | root          | pg_catalog         | pg_type                               | INSERT         | YES          | NO
 root    | root    | root          | pg_catalog         | pg_type                               | SELECT         | YES          | YES
 root    | root    | root          | pg_catalog         | pg_type                               | UPDATE         | YES          | NO
 root    | root    | root          | pg_catalog         | pg_type                               | DELETE         | YES          | NO
 root    | root    | root          | pg_catalog         | pg_type                               | TRUNCATE       | YES          | NO
 root    | root    | root          | pg_catalog         | pg_type                               | REFERENCES     | YES          | NO
 root    | root    | root          | pg_catalog         | pg_type                               | TRIGGER        | YES          | NO
 root    | root    | root          | pg_catalog         | pg_foreign_table                      | INSERT         | YES          | NO



should work?? because we have user, table_name and the privelage_type??

cc @StewartJingga @mabdh

**Comment by GrayFlash** [comment]
What should be the metadata model with which we can pass it??

current I can provide the list of owners actually using `Ownership *v1beta11.Ownership`

but user access is very different right?? So I don’t think this is what we should use.
Is there a model where I can pass something like, `username` and `privileges` he has. For e.g. 

`test_user` has `SELECT,INSERT,UPDATE,DELETE` and some other user `user2` only has `SELECT` privelege.

wdyt?? @StewartJingga @ravisuhag @mabdh

**Comment by StewartJingga** [comment]
@GrayFlash we can put those information inside `Properties.Attributes` fields inside `Table` model.
e.g.
```
&assetsv1beta1.Table{
	Properties: &facetsv1beta1.Properties{
		Attributes: utils.TryParseMapToProto(map[string]interface{}{
			"grants": []map[string]interface{}{
				{
					"user": "root",
					"privilege_types": []string{"SELECT", "INSERT"},
				},
				{
					"user": "myuser",
					"privilege_types": []string{"SELECT", "DELETE"},
				},
			},
		}),
	},
}
```

**Comment by mabdh** [comment]
@StewartJingga should we also need to have an `exclusion` feature so user might be able to not getting the dbuser-privilege information of `pg_catalog` or others metadata tables.

**Comment by StewartJingga** [comment]
> @StewartJingga should we also need to have an `exclusion` feature so user might be able to not getting the dbuser-privilege information of `pg_catalog` or others metadata tables.

I think it depends on how we extract this information. @GrayFlash do you plan to fetch this information per table? or doing it in bulk initially?

**Comment by GrayFlash** [comment]
> > @StewartJingga should we also need to have an `exclusion` feature so user might be able to not getting the dbuser-privilege information of `pg_catalog` or others metadata tables.
> 
> I think it depends on how we extract this information. @GrayFlash do you plan to fetch this information per table? or doing it in bulk initially?

I'm doing it per table so exclusion will not be an issue, as we have already excluded `pg_catalog` from extraction.
